# Generated by Django 3.0.4 on 2020-03-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repositorio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('arquivos', models.FileField(upload_to=repositorio.models.Arquivo.user_directory_path)),
                ('convidados', models.ManyToManyField(blank=True, related_name='rconvidados', to=settings.AUTH_USER_MODEL)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Arquivos',
                'ordering': ['nome'],
            },
        ),
    ]
